---
- name: Install dependencies for packer setup
  become: true
  apt:
    pkg:
      - curl
      - gnupg

- name: Add apt sining key for packer setup
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add repository for packer setup
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: packer
    state: present

- name: Install packer
  become: true
  apt:
    name: packer
    update_cache: yes
    state: present
